name: 'training_dbt'
version: '1.0'

profile: 'training_dbt'


source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  
clean-targets:      
    - "target"
    - "dbt_modules"


models:

  training_dbt:
    staging:
      materialized: view
          
  fishtown_analytics_ecommerce:
    transform:
      addresses:
        enabled: false
      order_items:
        enabled: false
      products:
        enabled: false
      customers:
        materialized: table
    vars:
      customers_table: "{{ref('stg_customers')}}"
      orders_table: "{{ref('stg_orders')}}"
      customer_aggregate_on: customer_id
      customer_join_on: customer_id
      order_items_table: "not using this"
      addresses_table: "not using this"
      products_table: "not using this"
